---
title: "Residuals and Residual Variation - Exercises"
output:
    html_document:
        keep_md: true
---

```{r setup, cache = FALSE, echo = FALSE, message = FALSE, warning = FALSE, tidy = FALSE}
require(knitr)
# make this an external chunk that can be included in any file
options(width = 100)
opts_chunk$set(message = F, error = F, warning = F, comment = NA, fig.align = 'center', dpi = 100, tidy = F, cache.path = '.cache/', fig.path = 'fig/')

options(xtable.type = 'html')
knit_hooks$set(inline = function(x) {
  if(is.numeric(x)) {
    round(x, getOption('digits'))
  } else {
    paste(as.character(x), collapse = ', ')
  }
})
knit_hooks$set(plot = knitr:::hook_plot_html)
```

## Question 1

Fit a linear regression model to the `father.son` dataset th the father as the predictor and the son as the outcome. Plot the son's height (horizontal axis) versus the residuals (vertical axis).

**ANSWER:** See plot.

```{r, Q1Ans}
library(UsingR)
library(ggplot2)
data(father.son)
father.son$resid <- lm(sheight ~ fheight, father.son)$residuals
ggplot(father.son, aes(x=sheight, y=resid)) +
    geom_point(size=5, color="darkgreen", alpha=0.5) +
    geom_smooth(method="lm", color="blue")
```

---